# Generated by Django 4.1.3 on 2022-12-10 11:42

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Playlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('desc', models.TextField(blank=True)),
                ('img', models.ImageField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('post_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('img', models.ImageField(upload_to='')),
                ('pub_date', models.DateField(auto_now=True)),
                ('category', models.CharField(blank=True, max_length=200)),
                ('sub_category', models.CharField(blank=True, max_length=200)),
                ('content', ckeditor.fields.RichTextField()),
                ('author', models.CharField(default='Codin India', max_length=150)),
                ('readtime', models.IntegerField()),
                ('dexc', models.TextField()),
                ('play', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Blog.playlist')),
            ],
        ),
    ]
