# Generated by Django 4.1.3 on 2022-12-10 17:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='dexc',
        ),
        migrations.RemoveField(
            model_name='blog',
            name='play',
        ),
    ]
